USE [master]
GO
/****** Object:  Database [CandyMarket]    Script Date: 5/20/2020 9:25:09 PM ******/
CREATE DATABASE [CandyMarket]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CandyMarket', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CandyMarket.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CandyMarket_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CandyMarket_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [CandyMarket] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CandyMarket].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CandyMarket] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CandyMarket] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CandyMarket] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CandyMarket] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CandyMarket] SET ARITHABORT OFF 
GO
ALTER DATABASE [CandyMarket] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CandyMarket] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CandyMarket] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CandyMarket] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CandyMarket] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CandyMarket] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CandyMarket] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CandyMarket] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CandyMarket] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CandyMarket] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CandyMarket] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CandyMarket] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CandyMarket] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CandyMarket] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CandyMarket] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CandyMarket] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CandyMarket] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CandyMarket] SET RECOVERY FULL 
GO
ALTER DATABASE [CandyMarket] SET  MULTI_USER 
GO
ALTER DATABASE [CandyMarket] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CandyMarket] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CandyMarket] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CandyMarket] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CandyMarket] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'CandyMarket', N'ON'
GO
ALTER DATABASE [CandyMarket] SET QUERY_STORE = OFF
GO
ALTER DATABASE [CandyMarket] SET  READ_WRITE 
GO
